Fix: broken Xdai ref
SmartInvoiceXYZ/smart-invoice pull request #148
Opened 2023-11-13 16:08 UTC by moconnell

- [x] replace ../deployments/xdai.json with ..gnosis.json

2023-11-14 02:01 UTC, psparacino requested changes
Also need to change the network value in deployments/gnosis, looks like it's still currently xdai. Also cam change in hardhat config. Every reference to xdai (except potentially block explorer urls can be changed to gnosis I believe

2023-11-16 08:50 UTC, moconnell commented
> Also need to change the network value in deployments/gnosis, looks like it's still currently xdai. Also cam change in hardhat config. Every reference to xdai (except potentially block explorer urls can be changed to gnosis I believe

ok, have fixed all the other locations I could find, apart from any references to the subgraph `psparacino/v1-xdai-smart-invoices`

2023-11-16 19:05 UTC, psparacino approved these changes
The comments don't preclude a merge in my opinion to test on develop.  More that we very likely need to update the hardhat version to be able to verify

2023-11-16 19:05 UTC, psparacino commented on packages/contracts/tasks/verify-blockscout.js
> +  100: "https://gnosis.blockscout.com/api",
I'm guessing our hardhat version is going to be too old to verify with this url. But maybe that's ok and we can just verify manually. Good incentive to also update the hardhat version, or even Foundry, but those are big and bigger lifts respectively.

2023-11-16 19:05 UTC, psparacino commented on packages/dapp/constants/index.js
> +  100: 'https://gnosis.blockscout.com',
same here

2023-11-16 19:48 UTC, merged